import type { UIMessage } from 'ai';
import type { ParsedResumePdf, UploadedResumePdf } from '@/lib/resume-pdf';
import { createGoogleGenerativeAI } from '@ai-sdk/google';
import { zValidator } from '@hono/zod-validator';
import { convertToModelMessages, stepCountIs, streamText } from 'ai';
import {
  collectUploadedResumePdfs,
  parseResumePdf,
  selectUploadedResumePdfs,
} from '@/lib/resume-pdf';
import { factory } from '@/server/factory';
import { chatRequestSchema } from './schema';
import {
  createExtractResumePdfStructuredInfoTool,
  createExtractResumePdfTextTool,
  createListUploadedResumePdfsTool,
  getResumeReviewFrameworkTool,
  getServerTimeTool,
} from './tools';
import { buildAutoJobDescription } from './utils';

const NORMALIZE_WHITESPACE_REGEX = /\s+/g;
const ROLE_KEYWORD_MAP: Array<{ keyword: RegExp, role: string }> = [
  { keyword: /行政/, role: '行政实习生' },
  { keyword: /人事|HR/, role: '人力资源实习生' },
  { keyword: /运营/, role: '运营实习生' },
  { keyword: /产品/, role: '产品实习生' },
  { keyword: /前端/, role: '前端开发实习生' },
  { keyword: /后端|服务端|后台/, role: '后端开发实习生' },
  { keyword: /测试|QA/, role: '测试实习生' },
  { keyword: /数据分析|数据/, role: '数据分析实习生' },
  { keyword: /设计|UI|UX/, role: '设计实习生' },
  { keyword: /财务/, role: '财务实习生' },
];
const ROLE_INFER_PATTERNS = [
  /(?:我需要招聘|我们需要招聘|需要招聘|招聘)\s*([^，。；\n]{1,24})/,
  /(?:我需要|我们需要|需要)\s*([^，。；\n]{1,24})(?:岗位|职位|方向|人员)?/,
];
const ROLE_STRIP_TERMS_REGEX = /(一名|一位|一个|若干|实习生|岗位|职位|方向|人员|的)/g;

function extractUserText(messages: UIMessage[]): string {
  return messages
    .filter(message => message.role === 'user')
    .flatMap(message => message.parts)
    .filter(part => part.type === 'text')
    .map(part => part.text)
    .join('\n')
    .trim();
}

function inferRoleFromText(text: string): string | null {
  const normalized = text.replace(NORMALIZE_WHITESPACE_REGEX, ' ').trim();

  if (!normalized) {
    return null;
  }

  for (const item of ROLE_KEYWORD_MAP) {
    if (item.keyword.test(normalized)) {
      return item.role;
    }
  }

  for (const pattern of ROLE_INFER_PATTERNS) {
    const match = normalized.match(pattern);

    if (!match?.[1]) {
      continue;
    }

    const role = match[1]
      .replace(ROLE_STRIP_TERMS_REGEX, '')
      .trim();

    if (role.length > 0) {
      return role.includes('实习') ? role : `${role}实习生`;
    }
  }

  return null;
}

export const chatRouter = factory.createApp().post(
  '/',
  zValidator('json', chatRequestSchema),
  async (c) => {
    const { jobDescription, messages } = c.req.valid('json');

    const apiKey = process.env.GOOGLE_GENERATIVE_AI_API_KEY;

    if (!apiKey) {
      return c.json(
        {
          error:
            'Missing GOOGLE_GENERATIVE_AI_API_KEY. Please configure your environment variables.',
        },
        500,
      );
    }

    const baseURL = process.env.GOOGLE_GENERATIVE_AI_BASE_URL?.trim();

    const provider = createGoogleGenerativeAI({
      apiKey,
      ...(baseURL ? { baseURL } : {}),
    });

    const modelId = process.env.GOOGLE_MODEL ?? 'gemini-3-flash-preview';
    const normalizedJobDescription = jobDescription?.trim();
    const uploadedResumePdfs = collectUploadedResumePdfs(messages);
    const uploadedResumeFiles = uploadedResumePdfs.length > 0;
    const userText = extractUserText(messages);
    const inferredRole = inferRoleFromText(userText);
    const autoGeneratedJd = inferredRole ? buildAutoJobDescription(inferredRole) : null;

    const parsedResumeCache = new Map<string, Promise<ParsedResumePdf>>();

    const parseUploadedResume = (file: UploadedResumePdf) => {
      const cached = parsedResumeCache.get(file.id);

      if (cached) {
        return cached;
      }

      const task = parseResumePdf(file);
      parsedResumeCache.set(file.id, task);
      return task;
    };

    const availableResumeNames = uploadedResumePdfs.map(
      (file, index) => `${index + 1}. ${file.filename}`,
    );

    const selectResumeFiles = (resumeName?: string) =>
      selectUploadedResumePdfs(uploadedResumePdfs, resumeName);

    const jdContext = normalizedJobDescription
      ? `设置中配置的 JD（次级上下文）：\n${normalizedJobDescription}`
      : '设置中未配置 JD。';

    const autoJdContext = autoGeneratedJd
      ? `根据用户文本自动生成的 JD：\n${autoGeneratedJd}`
      : '未能从用户文本中自动生成 JD。';

    const result = streamText({
      model: provider(modelId),
      system: `你是一名简历筛选助手。
你的目标是帮助招聘人员快速评估实习候选人。
回答保持简洁、结构化。
合适时请提供：整体建议（进入面试 / 暂缓 / 淘汰）、评分（0-100）、优势、风险以及后续面试追问问题。
JD 优先级规则：
1) 如果用户在对话中明确提供或更新了 JD，优先使用该 JD 作为主判断依据。
2) 如果用户只表达了招聘意图，例如“我需要招聘行政”，则使用自动生成的 JD 作为当前主要工作 JD。
3) 设置中配置的 JD 仅作为次级上下文使用。
4) 如果仍然缺少 JD，请明确说明你的假设并继续分析。
交互规则：
- 不要因为反复索取信息而阻塞用户。
- 如果存在简历文件，先立即给出首轮评估，再最多提出 3 个有针对性的补充问题。
- 如果信息不完整，给出带有置信度说明的暂定排序，而不是直接拒绝分析。
PDF 简历解析规则：
- PDF 工具是辅助工具。如果当前模型原生支持 PDF 理解，应优先使用原生分析结果。
- 如果用户要求分析或对比简历，且已上传 PDF，请先调用 list_uploaded_resume_pdfs。
- 然后主动调用 extract_resume_pdf_structured_info；当你需要逐字证据、冲突核验或更高置信度时，再调用 extract_resume_pdf_text。
- 对上传 PDF 的简历进行排序或对比时，在给出最终建议前，至少调用一个 PDF 工具。
- 如果上传的 PDF 中已经包含简历信息，不要要求用户手动粘贴这些内容。
当用户询问当前时间时，调用 get_server_time。
当用户询问筛选标准时，调用 get_resume_review_framework。
不要编造不可获得的事实。

${jdContext}

${autoJdContext}

已上传简历文件：${uploadedResumeFiles ? '是' : '否'}。`,
      messages: await convertToModelMessages(messages),
      stopWhen: stepCountIs(8),
      tools: {
        get_server_time: getServerTimeTool,
        get_resume_review_framework: getResumeReviewFrameworkTool,
        list_uploaded_resume_pdfs: createListUploadedResumePdfsTool({
          availableResumeNames,
          uploadedResumePdfs,
        }),
        extract_resume_pdf_text: createExtractResumePdfTextTool({
          availableResumeNames,
          parseUploadedResume,
          selectResumeFiles,
          uploadedResumePdfs,
        }),
        extract_resume_pdf_structured_info: createExtractResumePdfStructuredInfoTool({
          availableResumeNames,
          parseUploadedResume,
          selectResumeFiles,
          uploadedResumePdfs,
        }),
      },
    });

    return result.toUIMessageStreamResponse({
      sendReasoning: true,
      sendSources: true,
    });
  },
);
