import type { UIMessage } from 'ai';
import type { ParsedResumePdf, UploadedResumePdf } from '@/lib/resume-pdf';
import { createGoogleGenerativeAI } from '@ai-sdk/google';
import { zValidator } from '@hono/zod-validator';
import { convertToModelMessages, stepCountIs, streamText } from 'ai';
import { decodeDataUrl } from '@/lib/data-url';
import {
  collectUploadedResumePdfs,
  parseResumePdf,
  selectUploadedResumePdfs,
} from '@/lib/resume-pdf';
import { factory } from '@/server/factory';
import { chatRequestSchema } from './schema';
import {
  createExtractResumePdfStructuredInfoTool,
  createExtractResumePdfTextTool,
  createListUploadedResumePdfsTool,
  getResumeReviewFrameworkTool,
  getServerTimeTool,
} from './tools';
import { buildAutoJobDescription } from './utils';

const NORMALIZE_WHITESPACE_REGEX = /\s+/g;
const ROLE_KEYWORD_MAP: Array<{ keyword: RegExp, role: string }> = [
  { keyword: /行政/, role: '行政' },
  { keyword: /人事|HR/, role: '人力资源' },
  { keyword: /运营/, role: '运营' },
  { keyword: /产品/, role: '产品' },
  { keyword: /前端/, role: '前端开发' },
  { keyword: /后端|服务端|后台/, role: '后端开发' },
  { keyword: /测试|QA/, role: '测试' },
  { keyword: /数据分析|数据/, role: '数据分析' },
  { keyword: /设计|UI|UX/, role: '设计' },
  { keyword: /财务/, role: '财务' },
];
const ROLE_INFER_PATTERNS = [
  /(?:我需要招聘|我们需要招聘|需要招聘|招聘)\s*([^，。；\n]{1,24})/,
  /(?:我需要|我们需要|需要)\s*([^，。；\n]{1,24})(?:岗位|职位|方向|人员)?/,
];
const ROLE_STRIP_TERMS_REGEX = /(一名|一位|一个|若干|岗位|职位|方向|人员|的)/g;
const SERVER_TIME_ZONE = 'Asia/Shanghai';

function extractUserText(messages: UIMessage[]): string {
  return messages
    .filter(message => message.role === 'user')
    .flatMap(message => message.parts)
    .filter(part => part.type === 'text')
    .map(part => part.text)
    .join('\n')
    .trim();
}

function inferRoleFromText(text: string): string | null {
  const normalized = text.replace(NORMALIZE_WHITESPACE_REGEX, ' ').trim();

  if (!normalized) {
    return null;
  }

  for (const item of ROLE_KEYWORD_MAP) {
    if (item.keyword.test(normalized)) {
      return item.role;
    }
  }

  for (const pattern of ROLE_INFER_PATTERNS) {
    const match = normalized.match(pattern);

    if (!match?.[1]) {
      continue;
    }

    const role = match[1]
      .replace(ROLE_STRIP_TERMS_REGEX, '')
      .trim();

    if (role.length > 0) {
      return role;
    }
  }

  return null;
}

export const chatRouter = factory.createApp().post(
  '/',
  zValidator('json', chatRequestSchema),
  async (c) => {
    const { jobDescription, messages } = c.req.valid('json');

    const apiKey = process.env.GOOGLE_GENERATIVE_AI_API_KEY;

    if (!apiKey) {
      return c.json(
        {
          error:
            'Missing GOOGLE_GENERATIVE_AI_API_KEY. Please configure your environment variables.',
        },
        500,
      );
    }

    const baseURL = process.env.GOOGLE_GENERATIVE_AI_BASE_URL?.trim();

    const provider = createGoogleGenerativeAI({
      apiKey,
      ...(baseURL ? { baseURL } : {}),
    });

    const modelId = process.env.GOOGLE_MODEL ?? 'gemini-3-flash-preview';
    const normalizedJobDescription = jobDescription?.trim();
    const uploadedResumePdfs = collectUploadedResumePdfs(messages);
    const uploadedResumeFiles = uploadedResumePdfs.length > 0;
    const userText = extractUserText(messages);
    const inferredRole = inferRoleFromText(userText);
    const autoGeneratedJd = inferredRole ? buildAutoJobDescription(inferredRole) : null;
    const serverNow = new Date();
    const serverTimeContext = new Intl.DateTimeFormat('zh-CN', {
      dateStyle: 'full',
      timeStyle: 'long',
      timeZone: SERVER_TIME_ZONE,
    }).format(serverNow);

    const parsedResumeCache = new Map<string, Promise<ParsedResumePdf>>();

    const parseUploadedResume = (file: UploadedResumePdf) => {
      const cached = parsedResumeCache.get(file.id);

      if (cached) {
        return cached;
      }

      const task = parseResumePdf(file);
      parsedResumeCache.set(file.id, task);
      return task;
    };

    const availableResumeNames = uploadedResumePdfs.map(
      (file, index) => `${index + 1}. ${file.filename}`,
    );

    const selectResumeFiles = (resumeName?: string) =>
      selectUploadedResumePdfs(uploadedResumePdfs, resumeName);

    const jdContext = normalizedJobDescription
      ? `设置中配置的 JD（次级上下文）：\n${normalizedJobDescription}`
      : '设置中未配置 JD。';

    const autoJdContext = autoGeneratedJd
      ? `根据用户文本自动生成的 JD：\n${autoGeneratedJd}`
      : '未能从用户文本中自动生成 JD。';

    const result = streamText({
      model: provider(modelId),
      system: `你是一名简历筛选助手。
你的目标是帮助招聘人员快速评估候选人。
回答保持简洁、结构化。
默认简历分析框架：
- 无论用户是否逐项点名，只要是在做候选人简历分析，默认都要覆盖以下维度：候选人优点、候选人缺点、关键风险项、建议的团队定位、建议的职级定级。
- 如果信息足够，再补充整体建议（进入面试 / 暂缓 / 淘汰）、评分（0-100）以及后续面试追问问题。
- 团队定位要尽量落到可执行的团队类型或职责方向，例如：业务前端、平台前端、增长运营、通用后端、数据支持、项目协调。
- 职级定级要给出清晰的建议级别，并说明依据；若无法精确定级，也要给出区间或候选级别，例如：初级 / 初中级 / 中级 / 中高级 / 高级 / 资深 / 专家，或 P5-P6 候选。
- 关键风险项优先关注：时间线异常、经历真实性不足、职责和结果不清、频繁跳槽、能力与岗位不匹配、项目深度不足、管理边界不明确。
- 如果证据不足，明确标注“待核实”而不是编造结论。
- 默认输出模板按以下顺序组织，除非用户明确要求其他格式：1. 候选人结论；2. 候选人优点；3. 候选人缺点；4. 关键风险项；5. 建议团队定位；6. 建议职级定级；7. 是否建议进入下一轮；8. 建议追问问题。
- 每个栏目都尽量给出 2-4 条高价值要点；如果某栏证据不足，明确写“待核实”。
JD 优先级规则：
1) 如果用户在对话中明确提供或更新了 JD，优先使用该 JD 作为主判断依据。
2) 如果用户只表达了招聘意图，例如“我需要招聘行政”，则使用自动生成的 JD 作为当前主要工作 JD。
3) 设置中配置的 JD 仅作为次级上下文使用。
4) 如果仍然缺少 JD，请明确说明你的假设并继续分析。
交互规则：
- 不要因为反复索取信息而阻塞用户。
- 如果存在简历文件，先立即给出首轮评估，再最多提出 3 个有针对性的补充问题。
- 如果信息不完整，给出带有置信度说明的暂定排序，而不是直接拒绝分析。
时间规则：
- 当前服务端时间（${SERVER_TIME_ZONE}）是：${serverTimeContext}。
- 当你需要判断候选人的在职时长、工作年限、项目持续时间、是否仍在职或时间线是否合理时，应以上述服务端当前时间作为“现在”进行推断。
- 如果简历里的时间表达含糊（例如“至今”“最近”“目前”），默认按上述服务端当前时间理解，并在结论里明确说明。
- 做时间线分析时，优先抽取每段经历的起止时间，再判断总工作年限、是否仍在职、是否存在长空档、是否存在明显重叠、是否存在连续短经历或频繁跳槽信号。
- 如果需要更稳定的时间线判断，应主动调用 extract_resume_pdf_structured_info，优先利用其中的 timelineSummary 字段辅助判断。
- 对跳槽风险的判断要克制：只有出现连续短经历、明显空档、时间重叠、频繁变动且缺少结果支撑时，才将其列为关键风险项。
PDF 简历解析规则：
- PDF 工具是辅助工具。如果当前模型原生支持 PDF 理解，应优先使用原生分析结果。
- 如果用户要求分析或对比简历，且已上传 PDF，请先调用 list_uploaded_resume_pdfs。
- 然后主动调用 extract_resume_pdf_structured_info；当你需要逐字证据、冲突核验或更高置信度时，再调用 extract_resume_pdf_text。
- 对上传 PDF 的简历进行排序或对比时，在给出最终建议前，至少调用一个 PDF 工具。
- 如果上传的 PDF 中已经包含简历信息，不要要求用户手动粘贴这些内容。
- 只分析能够识别为候选人简历的有效 PDF 内容；如果某个 PDF 明显不是简历（例如合同、报价单、试卷、论文、产品文档、说明书、发票等），忽略该文件，不要把它纳入候选人分析、排序或对比。
- 如果上传文件里同时包含简历 PDF 和非简历 PDF，仅基于简历 PDF 继续分析，并在必要时简短说明已忽略非简历文件。
当用户询问当前时间时，调用 get_server_time。
当用户询问筛选标准时，调用 get_resume_review_framework。
不要编造不可获得的事实。

${jdContext}

${autoJdContext}

已上传简历文件：${uploadedResumeFiles ? '是' : '否'}。`,
      experimental_download: async requests => requests.map(({ url }) => {
        if (url.protocol !== 'data:') {
          return null;
        }

        const decoded = decodeDataUrl(url.toString());
        return {
          data: decoded.data,
          mediaType: decoded.mediaType,
        };
      }),
      messages: await convertToModelMessages(messages),
      stopWhen: stepCountIs(8),
      tools: {
        get_server_time: getServerTimeTool,
        get_resume_review_framework: getResumeReviewFrameworkTool,
        list_uploaded_resume_pdfs: createListUploadedResumePdfsTool({
          availableResumeNames,
          uploadedResumePdfs,
        }),
        extract_resume_pdf_text: createExtractResumePdfTextTool({
          availableResumeNames,
          parseUploadedResume,
          selectResumeFiles,
          uploadedResumePdfs,
        }),
        extract_resume_pdf_structured_info: createExtractResumePdfStructuredInfoTool({
          availableResumeNames,
          parseUploadedResume,
          selectResumeFiles,
          uploadedResumePdfs,
        }),
      },
    });

    return result.toUIMessageStreamResponse({
      sendReasoning: true,
      sendSources: true,
    });
  },
);
